class Binder:

    def __new__(cls, *args, **kwargs): ...

    def __init__(self, *args, **kwargs): ...

    def __del__(self, *args, **kwargs): ...

    def read(self, filename:str) -> str: ...

    def write(self, filename:str, data:str) -> None: ...